events {}

http {
    upstream calculadora {
        least_conn;

        #Maquina A
        server 192.168.1.12:30000;
        server 192.168.1.12:30001;
        server 192.168.1.12:30002;

        #Maquina B
        server 192.168.1.13:30000;
        server 192.168.1.13:30001;
        server 192.168.1.13:30002;
    }

    server {
        listen 8020;

        location / {
            proxy_set_header Host $host;
            proxy_pass http://calculadora;
        }
    }
}